package com.personal.ircclient.core.utils

object Localizer {
    private val strings = mapOf(
        "en" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Settings",
            "appearance" to "Appearance",
            "security_privacy" to "Security & Privacy",
            "audio_events" to "Audio & Events",
            "radio" to "Radio",
            "connectivity" to "Connectivity",
            "ascii_phrases" to "ASCII & Phrases",
            "about" to "About",
            "nav_servers" to "Servers",
            "nav_rooms" to "Rooms",
            "nav_privates" to "Privates",
            "nav_settings" to "Settings",
            "theme" to "Theme",
            "language" to "Language",
            "identity_color" to "Identity Color",
            "incoming_bubbles" to "Incoming Bubbles",
            "own_bubbles" to "Own Bubbles",
            "high_contrast" to "High Contrast",
            "enable_irc_colors" to "Enable IRC Colors",
            "only_friends_pv" to "Only Friends PV",
            "auto_response" to "Auto-response Message",
            "link_previews" to "Link Previews",
            "auto_load_images" to "Auto-load Images",
            "away_messages" to "Away Messages",
            "default_away" to "Default Away Message",
            "default_back" to "Default Back Message",
            "user_agent" to "UserAgent / RealName",
            "tts" to "Text-to-Speech",
            "sound_friend" to "Friend Join Sound",
            "sound_pm" to "Private Message Sound",
            "sound_notice" to "Notice Received Sound",
            "sound_mention" to "Mention Sound",
            "events_display" to "Events Display",
            "show_events" to "Show Events in Room",
            "joins" to "Joins",
            "parts" to "Parts",
            "quits" to "Quits",
            "nicks" to "Nick Changes",
            "kicks" to "Kicks",
            "bans" to "Bans",
            "enable_radio" to "Enable Radio Plugin",
            "station" to "Station",
            "stay_persistent" to "Stay Persistent",
            "search_engine" to "Search Engine URL",
            "use_proxy" to "Use Proxy",
            "host" to "Host",
            "port" to "Port",
            "version" to "Version",
            "check_updates" to "Check for Updates",
            "exit_app" to "Exit FenixIRC",
            "no_servers" to "No servers added yet.",
            "no_rooms" to "No active rooms here.",
            "no_privates" to "No private chats yet.",
            "no_ascii" to "No items saved.",
            "join_room" to "Join Room",
            "discover" to "Discover",
            "new_private" to "New Private",
            "friend_list" to "Friend List",
            "search_user" to "Search User",
            "add_new" to "Add New",
            "save" to "Save",
            "cancel" to "Cancel",
            "close" to "Close",
            "whois" to "Whois",
            "private_chat" to "Private Chat",
            "ignore" to "Ignore",
            "delete" to "Delete",
            "edit" to "Edit",
            "connect" to "Connect",
            "disconnect" to "Disconnect",
            "connect_all" to "Connect All",
            "disconnect_all" to "Disconnect All",
            "server_info" to "Server Info",
            "status" to "Status",
            "joined" to "JOINED",
            "banned" to "BANNED",
            "disconnected" to "DISCONNECTED",
            "delete_server" to "Delete Server",
            "delete_server_confirm" to "Are you sure you want to delete this server? History will be lost.",
            "clear_history" to "Clear History",
            "clear_history_confirm" to "Are you sure you want to clear chat history?",
            "loading_image_risk" to "Load Image (Privacy Risk)",
            "youtube_video" to "YouTube Video",
            "social_media_link" to "Social Media Link",
            "modified_by_script" to "Modified by script",
            "typing_message" to "Type a message...",
            "enter_command" to "Enter command...",
            "voice_message" to "Voice Message",
            "voice_message_ext" to "Voice Message (External)",
            "self_destruct" to "Self-Destruct Timer",
            "no_limit" to "No Limit",
            "copy_link" to "Copy Link",
            "search" to "Search",
            "music_search" to "Search Music",
            "quick_search" to "Quick Search",
            "kick_user" to "Kick User",
            "ban_user" to "Ban User",
            "op_user" to "Give Op",
            "deop_user" to "Take Op",
            "copy_text" to "Copy Text",
            "copy_nick" to "Copy Nick",
            "notice" to "Notice",
            "user_management" to "User Management",
            "friends" to "Friends",
            "ignored" to "Ignored",
            "silenced" to "Silenced",
            "select_server" to "Select Server",
            "remove" to "Remove",
            "mode" to "Mode",
            "filter_channels" to "Filter Channels",
            "min_users" to "Min Users",
            "apply" to "Apply",
            "users" to "users",
            "no_topic" to "No topic set",
            "add_server" to "Add Server",
            "edit_server" to "Edit Server",
            "connection" to "Connection",
            "identity" to "Identity",
            "advanced_sasl" to "Advanced - SASL",
            "advanced_bouncer" to "Advanced - Bouncer",
            "preferences" to "Preferences",
            "network_name" to "Network Name",
            "server_host" to "Server Host",
            "use_ssl" to "Use SSL/TLS",
            "allow_plain_text" to "Allow Plain Text Connection",
            "nickname" to "Nickname",
            "alt_nickname" to "Alternative Nickname",
            "random_nick" to "Generate Random Nick",
            "username" to "Username",
            "real_name" to "Real Name",
            "server_password" to "Server Password",
            "use_sasl" to "Use SASL Authentication",
            "sasl_username" to "SASL Username",
            "sasl_password" to "SASL Password",
            "use_bouncer" to "Connection through Bouncer",
            "bouncer_network" to "Bouncer Network/Tag",
            "auto_connect" to "Auto-Connect on Start",
            "reconnect_channels" to "Auto-Join Channels",
            "encoding" to "Encoding / Alphabet",
            "save_changes" to "Save Changes",
            "total_users" to "Total users"
        ),
        "es" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Ajustes",
            "appearance" to "Apariencia",
            "security_privacy" to "Seguridad y Privacidad",
            "audio_events" to "Audio y Eventos",
            "radio" to "Radio",
            "connectivity" to "Conectividad",
            "ascii_phrases" to "ASCII y Frases",
            "about" to "Acerca de",
            "nav_servers" to "Servidores",
            "nav_rooms" to "Salas",
            "nav_privates" to "Privados",
            "nav_settings" to "Ajustes",
            "theme" to "Tema",
            "language" to "Idioma",
            "identity_color" to "Color de Identidad",
            "incoming_bubbles" to "Burbujas Entrantes",
            "own_bubbles" to "Mis Burbujas",
            "high_contrast" to "Alto Contraste",
            "enable_irc_colors" to "Habilitar Colores IRC",
            "only_friends_pv" to "Solo Amigos en PV",
            "auto_response" to "Mensaje de Auto-respuesta",
            "link_previews" to "Previsualizar Enlaces",
            "auto_load_images" to "Auto-cargar Imágenes",
            "away_messages" to "Mensajes de Ausencia",
            "default_away" to "Mensaje de Ausencia por Defecto",
            "default_back" to "Mensaje de Regreso por Defecto",
            "user_agent" to "UserAgent / Nombre Real",
            "tts" to "Texto a Voz",
            "sound_friend" to "Sonido Entrada Amigo",
            "sound_pm" to "Sonido Mensaje Privado",
            "sound_notice" to "Sonido de Aviso",
            "sound_mention" to "Sonido de Mención",
            "events_display" to "Visualización de Eventos",
            "show_events" to "Mostrar Eventos en Sala",
            "joins" to "Entradas",
            "parts" to "Salidas",
            "quits" to "Desconexiones",
            "nicks" to "Cambios de Nick",
            "kicks" to "Expulsiones",
            "bans" to "Baneos",
            "enable_radio" to "Habilitar Plugin de Radio",
            "station" to "Estación",
            "stay_persistent" to "Mantener Conexión",
            "search_engine" to "URL del Buscador",
            "use_proxy" to "Usar Proxy",
            "host" to "Host",
            "port" to "Puerto",
            "version" to "Versión",
            "check_updates" to "Buscar Actualizaciones",
            "exit_app" to "Salir de FenixIRC",
            "no_servers" to "No hay servidores añadidos.",
            "no_rooms" to "No hay salas activas.",
            "no_privates" to "No hay chats privados.",
            "no_ascii" to "No hay elementos guardados.",
            "join_room" to "Entrar en Sala",
            "discover" to "Descubrir",
            "new_private" to "Nuevo Privado",
            "friend_list" to "Lista de Amigos",
            "search_user" to "Buscar Usuario",
            "add_new" to "Añadir Nuevo",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "close" to "Cerrar",
            "whois" to "Whois",
            "private_chat" to "Chat Privado",
            "ignore" to "Ignorar",
            "delete" to "Eliminar",
            "edit" to "Editar",
            "connect" to "Conectar",
            "disconnect" to "Desconectar",
            "connect_all" to "Conectar Todo",
            "disconnect_all" to "Desconectar Todo",
            "server_info" to "Info del Servidor",
            "status" to "Estado",
            "joined" to "CONECTADO",
            "banned" to "BANEADO",
            "disconnected" to "DESCONECTADO",
            "delete_server" to "Eliminar Servidor",
            "delete_server_confirm" to "¿Estás seguro de eliminar este servidor? El historial se perderá.",
            "clear_history" to "Borrar Historial",
            "clear_history_confirm" to "¿Estás seguro de borrar el historial de chat?",
            "loading_image_risk" to "Cargar Imagen (Riesgo de Privacidad)",
            "youtube_video" to "Vídeo de YouTube",
            "social_media_link" to "Enlace de Redes Sociales",
            "modified_by_script" to "Modificado por script",
            "typing_message" to "Escribe un mensaje...",
            "enter_command" to "Escribe un comando...",
            "voice_message" to "Mensaje de voz",
            "voice_message_ext" to "Mensaje de voz (Externo)",
            "self_destruct" to "Temporizador de auto-destrucción",
            "no_limit" to "Sin Límite",
            "copy_link" to "Copiar Enlace",
            "search" to "Buscar",
            "music_search" to "Buscar Música",
            "quick_search" to "Búsqueda Rápida",
            "kick_user" to "Expulsar Usuario",
            "ban_user" to "Banear Usuario",
            "op_user" to "Dar Op",
            "deop_user" to "Quitar Op",
            "copy_text" to "Copiar Texto",
            "copy_nick" to "Copiar Nick",
            "notice" to "Aviso",
            "user_management" to "Gestión de Usuarios",
            "friends" to "Amigos",
            "ignored" to "Ignorados",
            "silenced" to "Silenciados",
            "select_server" to "Seleccionar Servidor",
            "remove" to "Eliminar",
            "mode" to "Modo",
            "filter_channels" to "Filtrar Canales",
            "min_users" to "Mínimo de Usuarios",
            "apply" to "Aplicar",
            "users" to "usuarios",
            "no_topic" to "Sin tema definido",
            "add_server" to "Añadir Servidor",
            "edit_server" to "Editar Servidor",
            "connection" to "Conexión",
            "identity" to "Identidad",
            "advanced_sasl" to "Avanzado - SASL",
            "advanced_bouncer" to "Avanzado - Bouncer",
            "preferences" to "Preferencias",
            "network_name" to "Nombre de Red",
            "server_host" to "Host del Servidor",
            "use_ssl" to "Usar SSL/TLS",
            "allow_plain_text" to "Permitir Conexión en Texto Plano",
            "nickname" to "Nickname",
            "alt_nickname" to "Nickname Alternativo",
            "random_nick" to "Generar Nick Aleatorio",
            "username" to "Usuario (Identidad)",
            "real_name" to "Nombre Real",
            "server_password" to "Contraseña de Servidor",
            "use_sasl" to "Usar Autenticación SASL",
            "sasl_username" to "Usuario SASL",
            "sasl_password" to "Contraseña SASL",
            "use_bouncer" to "Conexión vía Bouncer",
            "bouncer_network" to "Red/Tag de Bouncer",
            "auto_connect" to "Auto-Conectar al Inicio",
            "reconnect_channels" to "Reconectar Canales Abiertos",
            "encoding" to "Codificación / Alfabeto",
            "save_changes" to "Guardar Cambios",
            "total_users" to "Usuarios totales"
        ),
        "fr" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Paramètres",
            "appearance" to "Apparence",
            "security_privacy" to "Sécurité et Privacité",
            "audio_events" to "Audio et Événements",
            "radio" to "Radio",
            "connectivity" to "Connectivité",
            "ascii_phrases" to "ASCII et Phrases",
            "about" to "À Propos",
            "nav_servers" to "Serveurs",
            "nav_rooms" to "Salons",
            "nav_privates" to "Privés",
            "nav_settings" to "Paramètres",
            "theme" to "Thème",
            "language" to "Langue",
            "identity_color" to "Couleur d'Identité",
            "incoming_bubbles" to "Bulles Entrantes",
            "own_bubbles" to "Mes Bulles",
            "high_contrast" to "Haut Contraste",
            "enable_irc_colors" to "Activer Couleurs IRC",
            "only_friends_pv" to "Amis Uniquement en PV",
            "auto_response" to "Message d'Auto-réponse",
            "link_previews" to "Aperçu des Liens",
            "auto_load_images" to "Auto-chargement Images",
            "away_messages" to "Messages d'Absence",
            "default_away" to "Message d'Absence par Défaut",
            "default_back" to "Message de Retour par Défaut",
            "user_agent" to "UserAgent / Nom Réel",
            "tts" to "Synthèse Vocale",
            "sound_friend" to "Son Entrée Ami",
            "sound_pm" to "Son Message Privé",
            "sound_notice" to "Son d'Avis",
            "sound_mention" to "Son de Mention",
            "events_display" to "Affichage des Événements",
            "show_events" to "Afficher Événements en Salon",
            "joins" to "Entrées",
            "parts" to "Sorties",
            "quits" to "Quittes",
            "nicks" to "Changements de Nick",
            "kicks" to "Expulsions",
            "bans" to "Bannissements",
            "enable_radio" to "Activer Plugin Radio",
            "station" to "Station",
            "stay_persistent" to "Rester Persistant",
            "search_engine" to "URL du Moteur de Recherche",
            "use_proxy" to "Utiliser un Proxy",
            "host" to "Hôte",
            "port" to "Port",
            "version" to "Version",
            "check_updates" to "Mises à Jour",
            "exit_app" to "Quitter FenixIRC",
            "no_servers" to "Aucun serveur ajouté.",
            "no_rooms" to "Aucun salon actif.",
            "no_privates" to "Aucun chat privé.",
            "no_ascii" to "Aucun élément enregistré.",
            "join_room" to "Rejoindre un Salon",
            "discover" to "Découvrir",
            "new_private" to "Nouveau Privé",
            "friend_list" to "Liste d'Amis",
            "search_user" to "Chercher Utilisateur",
            "add_new" to "Ajouter Nouveau",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "close" to "Fermer",
            "whois" to "Whois",
            "private_chat" to "Chat Privé",
            "ignore" to "Ignorer",
            "delete" to "Supprimer",
            "edit" to "Modifier",
            "connect" to "Connecter",
            "disconnect" to "Déconnecter",
            "connect_all" to "Tout Connecter",
            "disconnect_all" to "Tout Déconnecter",
            "server_info" to "Infos Serveur",
            "status" to "Statut",
            "joined" to "REJOINT",
            "banned" to "BANNI",
            "disconnected" to "DÉCONNECTÉ",
            "delete_server" to "Supprimer Serveur",
            "delete_server_confirm" to "Voulez-vous supprimer ce serveur ? L'historique sera perdu.",
            "clear_history" to "Effacer l'historique",
            "clear_history_confirm" to "Voulez-vous effacer l'historique du chat ?",
            "loading_image_risk" to "Charger l'image (Risque de confidentialité)",
            "youtube_video" to "Vidéo YouTube",
            "social_media_link" to "Lien vers les réseaux sociaux",
            "modified_by_script" to "Modifié par script",
            "typing_message" to "Tapez un message...",
            "enter_command" to "Tapez une commande...",
            "voice_message" to "Message vocal",
            "voice_message_ext" to "Message vocal (externe)",
            "self_destruct" to "Minuteur d'autodestruction",
            "no_limit" to "Sans limite",
            "copy_link" to "Copier le lien",
            "search" to "Rechercher",
            "music_search" to "Rechercher de la musique",
            "quick_search" to "Recherche rapide",
            "kick_user" to "Expulser l'utilisateur",
            "ban_user" to "Bannir l'utilisateur",
            "op_user" to "Donner Op",
            "deop_user" to "Prendre Op",
            "copy_text" to "Copier le texte",
            "copy_nick" to "Copiar le pseudo",
            "notice" to "Avis",
            "user_management" to "Gestion des utilisateurs",
            "friends" to "Amis",
            "ignored" to "Ignorés",
            "silenced" to "Silencieux",
            "select_server" to "Sélectionner un serveur",
            "remove" to "Supprimer",
            "mode" to "Mode",
            "filter_channels" to "Filtrer les salons",
            "min_users" to "Utilisateurs minimum",
            "apply" to "Appliquer",
            "users" to "utilisateurs",
            "no_topic" to "Aucun sujet défini",
            "add_server" to "Ajouter Serveur",
            "edit_server" to "Modifier Serveur",
            "connection" to "Connexion",
            "identity" to "Identité",
            "advanced_sasl" to "Avancé - SASL",
            "advanced_bouncer" to "Avancé - Bouncer",
            "preferences" to "Préférences",
            "network_name" to "Nom du Réseau",
            "server_host" to "Hôte du Serveur",
            "use_ssl" to "Utiliser SSL/TLS",
            "allow_plain_text" to "Permettre Connexion Texte",
            "nickname" to "Pseudo",
            "alt_nickname" to "Pseudo Alternatif",
            "random_nick" to "Pseudo Aléatoire",
            "username" to "Utilisateur (Identité)",
            "real_name" to "Nom Réel",
            "server_password" to "Mot de Passe Serveur",
            "use_sasl" to "Utiliser Authentification SASL",
            "sasl_username" to "Utilisateur SASL",
            "sasl_password" to "Mot de Passe SASL",
            "use_bouncer" to "Connexion via Bouncer",
            "bouncer_network" to "Réseau/Tag de Bouncer",
            "auto_connect" to "Auto-Connexion au Démarrage",
            "reconnect_channels" to "Rejoindre Salons Ouverts",
            "encoding" to "Encodage / Alphabet",
            "save_changes" to "Enregistrer Modifications"
        ),
        "de" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Einstellungen",
            "appearance" to "Aussehen",
            "security_privacy" to "Sicherheit und Datenschutz",
            "audio_events" to "Audio und Ereignisse",
            "radio" to "Radio",
            "connectivity" to "Konnektivität",
            "ascii_phrases" to "ASCII und Phrasen",
            "about" to "Über",
            "nav_servers" to "Server",
            "nav_rooms" to "Räume",
            "nav_privates" to "Privates",
            "nav_settings" to "Einstellungen",
            "theme" to "Thema",
            "language" to "Sprache",
            "identity_color" to "Identitätsfarbe",
            "incoming_bubbles" to "Eingehende Blasen",
            "own_bubbles" to "Eigene Blasen",
            "high_contrast" to "Hoher Kontrast",
            "enable_irc_colors" to "IRC-Farben Aktivieren",
            "only_friends_pv" to "Nur Freunde im PV",
            "auto_response" to "Auto-Antwort-Nachricht",
            "link_previews" to "Link-Vorschauen",
            "auto_load_images" to "Auto-laden Bilder",
            "away_messages" to "Abwesenheitsnachrichten",
            "default_away" to "Standard-Abwesenheit",
            "default_back" to "Standard-Rückkehr",
            "user_agent" to "UserAgent / Realname",
            "tts" to "Text-zu-Sprache",
            "sound_friend" to "Freund-Eintritt Sound",
            "sound_pm" to "Privatnachricht Sound",
            "sound_notice" to "Mitteilung Sound",
            "sound_mention" to "Erwähnung Sound",
            "events_display" to "Ereignisanzeige",
            "show_events" to "Ereignisse im Raum Zeigen",
            "joins" to "Eintritte",
            "parts" to "Austritte",
            "quits" to "Beendigungen",
            "nicks" to "Nickänderungen",
            "kicks" to "Rauswürfe",
            "bans" to "Bannungen",
            "enable_radio" to "Radio-Plugin Aktivieren",
            "station" to "Station",
            "stay_persistent" to "Beständig Bleiben",
            "search_engine" to "Suchmaschinen-URL",
            "use_proxy" to "Proxy Verwenden",
            "host" to "Host",
            "port" to "Port",
            "version" to "Version",
            "check_updates" to "Auf Updates Prüfen",
            "exit_app" to "FenixIRC Beenden",
            "no_servers" to "Noch keine Server hinzugefügt.",
            "no_rooms" to "Keine aktiven Räume.",
            "no_privates" to "Noch keine privaten Chats.",
            "no_ascii" to "Keine Elemente gespeichert.",
            "join_room" to "Raum Betreten",
            "discover" to "Entdecken",
            "new_private" to "Neues Privates",
            "friend_list" to "Freundesliste",
            "search_user" to "Benutzer Suchen",
            "add_new" to "Neu Hinzufügen",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "close" to "Schließen",
            "whois" to "Whois",
            "private_chat" to "Privater Chat",
            "ignore" to "Ignorieren",
            "delete" to "Löschen",
            "edit" to "Bearbeiten",
            "connect" to "Verbinden",
            "disconnect" to "Trennen",
            "connect_all" to "Alle Verbinden",
            "disconnect_all" to "Alle Trennen",
            "server_info" to "Server-Info",
            "status" to "Status",
            "joined" to "BEIGETRETEN",
            "banned" to "GEBANNT",
            "disconnected" to "GETRENNT",
            "delete_server" to "Server löschen",
            "delete_server_confirm" to "Möchten Sie diesen Server wirklich löschen? Der Verlauf geht verloren.",
            "clear_history" to "Verlauf löschen",
            "clear_history_confirm" to "Möchten Sie den Chatverlauf wirklich löschen?",
            "loading_image_risk" to "Bild laden (Datenschutzrisiko)",
            "youtube_video" to "YouTube-Video",
            "social_media_link" to "Social-Media-Link",
            "modified_by_script" to "Durch Skript geändert",
            "typing_message" to "Nachricht eingeben...",
            "enter_command" to "Befehl eingeben...",
            "voice_message" to "Sprachnachricht",
            "voice_message_ext" to "Sprachnachricht (extern)",
            "self_destruct" to "Selbstzerstörungstimer",
            "no_limit" to "Keine Begrenzung",
            "copy_link" to "Link kopieren",
            "search" to "Suchen",
            "music_search" to "Musik suchen",
            "quick_search" to "Schnellsuche",
            "kick_user" to "Benutzer rauswerfen",
            "ban_user" to "Benutzer bannen",
            "op_user" to "Op geben",
            "deop_user" to "Op nehmen",
            "copy_text" to "Text kopieren",
            "copy_nick" to "Pseudo kopieren",
            "notice" to "Mitteilung",
            "user_management" to "Benutzerverwaltung",
            "friends" to "Freunde",
            "ignored" to "Ignoriert",
            "silenced" to "Stummgeschaltet",
            "select_server" to "Server auswählen",
            "remove" to "Entfernen",
            "mode" to "Modus",
            "filter_channels" to "Kanäle filtern",
            "min_users" to "Mindestbenutzer",
            "apply" to "Anwenden",
            "users" to "Benutzer",
            "no_topic" to "Kein Thema festgelegt",
            "add_server" to "Server hinzufügen",
            "edit_server" to "Server bearbeiten",
            "connection" to "Verbindung",
            "identity" to "Identität",
            "advanced_sasl" to "Erweitert - SASL",
            "advanced_bouncer" to "Erweitert - Bouncer",
            "preferences" to "Präferenzen",
            "network_name" to "Netzwerkname",
            "server_host" to "Server-Host",
            "use_ssl" to "SSL/TLS verwenden",
            "allow_plain_text" to "Klartext-Verbindung erlauben",
            "nickname" to "Spitzname",
            "alt_nickname" to "Alternativer Spitzname",
            "random_nick" to "Zufälligen Nick generieren",
            "username" to "Benutzername (Identität)",
            "real_name" to "Realname",
            "server_password" to "Server-Passwort",
            "use_sasl" to "SASL-Authentifizierung verwenden",
            "sasl_username" to "SASL-Benutzername",
            "sasl_password" to "SASL-Passwort",
            "use_bouncer" to "Verbindung über Bouncer",
            "bouncer_network" to "Bouncer Netzwerk/Tag",
            "auto_connect" to "Auto-Connect bei Start",
            "reconnect_channels" to "Offene Kanäle wieder beitreten",
            "encoding" to "Codierung / Alphabet",
            "save_changes" to "Änderungen speichern"
        ),
        "pt" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Configurações",
            "appearance" to "Aparência",
            "security_privacy" to "Segurança e Privacidade",
            "audio_events" to "Áudio e Eventos",
            "radio" to "Rádio",
            "connectivity" to "Conectividade",
            "ascii_phrases" to "ASCII e Frases",
            "about" to "Sobre",
            "nav_servers" to "Servidores",
            "nav_rooms" to "Salas",
            "nav_privates" to "Privados",
            "nav_settings" to "Config",
            "theme" to "Tema",
            "language" to "Idioma",
            "identity_color" to "Cor de Identidade",
            "incoming_bubbles" to "Balões de Entrada",
            "own_bubbles" to "Meus Balões",
            "high_contrast" to "Alto Contraste",
            "enable_irc_colors" to "Habilitar Cores IRC",
            "only_friends_pv" to "Apenas Amigos no PV",
            "auto_response" to "Mensagem de Auto-resposta",
            "link_previews" to "Pré-visualizar Links",
            "auto_load_images" to "Auto-carregar Imagens",
            "away_messages" to "Mensagens de Ausência",
            "default_away" to "Mensagem Ausência Padrão",
            "default_back" to "Mensagem Retorno Padrão",
            "user_agent" to "UserAgent / Nome Real",
            "tts" to "Texto para Voz",
            "sound_friend" to "Som Entrada Amigo",
            "sound_pm" to "Som Mensagem Privada",
            "sound_notice" to "Som de Aviso",
            "sound_mention" to "Som de Menção",
            "events_display" to "Exibição de Eventos",
            "show_events" to "Mostrar Eventos na Sala",
            "joins" to "Entradas",
            "parts" to "Saídas",
            "quits" to "Desconexões",
            "nicks" to "Trocas de Nick",
            "kicks" to "Expulsões",
            "bans" to "Banimentos",
            "enable_radio" to "Habilitar Plugin de Rádio",
            "station" to "Estação",
            "stay_persistent" to "Permanecer Persistente",
            "search_engine" to "URL do Buscador",
            "use_proxy" to "Usar Proxy",
            "host" to "Host",
            "port" to "Porta",
            "version" to "Versão",
            "check_updates" to "Buscar Atualizaciones",
            "exit_app" to "Sair do FenixIRC",
            "no_servers" to "Nenhum servidor adicionado.",
            "no_rooms" to "Nenhuma sala activa.",
            "no_privates" to "Nenhum chat privado.",
            "no_ascii" to "Nenhum item salvo.",
            "join_room" to "Entrar na Sala",
            "discover" to "Descubrir",
            "new_private" to "Novo Privado",
            "friend_list" to "Lista de Amigos",
            "search_user" to "Buscar Usuário",
            "add_new" to "Adicionar Novo",
            "save" to "Salvar",
            "cancel" to "Cancelar",
            "close" to "Fechar",
            "whois" to "Whois",
            "private_chat" to "Chat Privado",
            "ignore" to "Ignorar",
            "delete" to "Eliminar",
            "edit" to "Editar",
            "connect" to "Conectar",
            "disconnect" to "Desconectar",
            "connect_all" to "Conectar Tudo",
            "disconnect_all" to "Desconectar Tudo",
            "server_info" to "Info do Servidor",
            "status" to "Estado",
            "joined" to "CONECTADO",
            "banned" to "BANIDO",
            "disconnected" to "DESCONECTADO",
            "delete_server" to "Excluir servidor",
            "delete_server_confirm" to "Tem certeza que deseja excluir este servidor? O histórico será perdido.",
            "clear_history" to "Limpar histórico",
            "clear_history_confirm" to "Tem certeza que deseja limpar o histórico de chat?",
            "loading_image_risk" to "Carregar imagem (risco de privacidade)",
            "youtube_video" to "Vídeo do YouTube",
            "social_media_link" to "Link de rede social",
            "modified_by_script" to "Modificado por script",
            "typing_message" to "Digite uma mensagem...",
            "enter_command" to "Digite um comando...",
            "voice_message" to "Mensagem de voz",
            "voice_message_ext" to "Mensagem de voz (externa)",
            "self_destruct" to "Temporizador de autodestruição",
            "no_limit" to "Sem limite",
            "copy_link" to "Copiar link",
            "search" to "Buscar",
            "music_search" to "Buscar música",
            "quick_search" to "Busca rápida",
            "kick_user" to "Expulsar usuário",
            "ban_user" to "Banir usuário",
            "op_user" to "Dar Op",
            "deop_user" to "Tirar Op",
            "copy_text" to "Copiar texto",
            "copy_nick" to "Copiar Nick",
            "notice" to "Aviso",
            "user_management" to "Gerenciamento de usuários",
            "friends" to "Amigos",
            "ignored" to "Ignorados",
            "silenced" to "Silenciados",
            "select_server" to "Selecionar servidor",
            "remove" to "Remover",
            "mode" to "Modo",
            "filter_channels" to "Filtrar canais",
            "min_users" to "Mínimo de usuários",
            "apply" to "Aplicar",
            "users" to "usuários",
            "no_topic" to "Nenhum tópico definido",
            "add_server" to "Adicionar Servidor",
            "edit_server" to "Editar Servidor",
            "connection" to "Conexão",
            "identity" to "Identidade",
            "advanced_sasl" to "Avançado - SASL",
            "advanced_bouncer" to "Avançado - Bouncer",
            "preferences" to "Preferências",
            "network_name" to "Nome da Rede",
            "server_host" to "Host do Servidor",
            "use_ssl" to "Usar SSL/TLS",
            "allow_plain_text" to "Permitir Conexão em Texto Plano",
            "nickname" to "Nickname",
            "alt_nickname" to "Nickname Alternativo",
            "random_nick" to "Gerar Nick Aleatório",
            "username" to "Usuário (Identidade)",
            "real_name" to "Nome Real",
            "server_password" to "Senha do Servidor",
            "use_sasl" to "Usar Autenticação SASL",
            "sasl_username" to "Usuário SASL",
            "sasl_password" to "Senha SASL",
            "use_bouncer" to "Conexão via Bouncer",
            "bouncer_network" to "Rede/Tag de Bouncer",
            "auto_connect" to "Auto-Conectar ao Iniciar",
            "reconnect_channels" to "Entrar em Canais Abertos",
            "encoding" to "Codificação / Alfabeto",
            "save_changes" to "Salvar Alterações"
        ),
        "zh" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "设置",
            "appearance" to "外观",
            "security_privacy" to "安全与隐私",
            "audio_events" to "音频与事件",
            "radio" to "电台",
            "connectivity" to "连接性",
            "ascii_phrases" to "ASCII 和短语",
            "about" to "关于",
            "nav_servers" to "服务器",
            "nav_rooms" to "房间",
            "nav_privates" to "私聊",
            "nav_settings" to "设置",
            "theme" to "主题",
            "language" to "语言",
            "identity_color" to "身份颜色",
            "incoming_bubbles" to "接收气泡",
            "own_bubbles" to "自身气泡",
            "high_contrast" to "高对比度",
            "enable_irc_colors" to "启用 IRC 颜色",
            "only_friends_pv" to "仅限好友私聊",
            "auto_response" to "自动回复消息",
            "link_previews" to "链接预览",
            "auto_load_images" to "自动加载图片",
            "away_messages" to "离开消息",
            "default_away" to "默认离开消息",
            "default_back" to "默认返回消息",
            "user_agent" to "用户代理 / 真实姓名",
            "tts" to "文本转语音",
            "sound_friend" to "好友加入音效",
            "sound_pm" to "私聊消息音效",
            "sound_notice" to "通知音效",
            "sound_mention" to "提及音效",
            "events_display" to "事件显示",
            "show_events" to "房间内显示事件",
            "joins" to "加入",
            "parts" to "离开",
            "quits" to "退出",
            "nicks" to "昵称更改",
            "kicks" to "踢出",
            "bans" to "封禁",
            "enable_radio" to "启用电台插件",
            "station" to "电台",
            "stay_persistent" to "保持后台运行",
            "search_engine" to "搜索引擎 URL",
            "use_proxy" to "使用代理",
            "host" to "主机",
            "port" to "端口",
            "version" to "版本",
            "check_updates" to "检查更新",
            "exit_app" to "退出 FenixIRC",
            "no_servers" to "尚未添加服务器。",
            "no_rooms" to "没有活动房间。",
            "no_privates" to "尚未有私聊。",
            "no_ascii" to "没有保存的项目。",
            "join_room" to "加入房间",
            "discover" to "发现",
            "new_private" to "新建私聊",
            "friend_list" to "好友列表",
            "search_user" to "搜索用户",
            "add_new" to "添加新项",
            "save" to "保存",
            "cancel" to "取消",
            "close" to "关闭",
            "whois" to "Whois",
            "private_chat" to "私聊",
            "ignore" to "忽略",
            "delete" to "删除",
            "edit" to "编辑",
            "connect" to "连接",
            "disconnect" to "断开连接",
            "connect_all" to "连接全部",
            "disconnect_all" to "断开全部",
            "server_info" to "服务器信息",
            "status" to "状态",
            "joined" to "已加入",
            "banned" to "已封禁",
            "disconnected" to "已断开",
            "delete_server" to "删除服务器",
            "delete_server_confirm" to "您确定要删除此服务器吗？历史记录将丢失。",
            "clear_history" to "清除历史记录",
            "clear_history_confirm" to "您确定要清除聊天记录吗？",
            "loading_image_risk" to "加载图像（隐私风险）",
            "youtube_video" to "YouTube 视频",
            "social_media_link" to "社交媒体链接",
            "modified_by_script" to "由脚本修改",
            "typing_message" to "输入消息...",
            "enter_command" to "输入命令...",
            "voice_message" to "语音消息",
            "voice_message_ext" to "语音消息（外部）",
            "self_destruct" to "自毁计时器",
            "no_limit" to "无限制",
            "copy_link" to "复制链接",
            "search" to "搜索",
            "music_search" to "搜索音乐",
            "quick_search" to "快速搜索",
            "kick_user" to "踢出用户",
            "ban_user" to "封禁用户",
            "op_user" to "赋予 Op",
            "deop_user" to "取消 Op",
            "copy_text" to "复制文本",
            "copy_nick" to "复制昵称",
            "notice" to "通知",
            "user_management" to "用户管理",
            "friends" to "好友",
            "ignored" to "已忽略",
            "silenced" to "已静音",
            "select_server" to "选择服务器",
            "remove" to "移除",
            "mode" to "模式",
            "filter_channels" to "筛选频道",
            "min_users" to "最小用户数",
            "apply" to "应用",
            "users" to "用户",
            "no_topic" to "未设置话题",
            "add_server" to "添加服务器",
            "edit_server" to "编辑服务器",
            "connection" to "连接",
            "identity" to "身份",
            "advanced_sasl" to "高级 - SASL",
            "advanced_bouncer" to "高级 - Bouncer",
            "preferences" to "首选项",
            "network_name" to "网络名称",
            "server_host" to "服务器地址",
            "use_ssl" to "使用 SSL/TLS",
            "allow_plain_text" to "允许明文连接",
            "nickname" to "昵称",
            "alt_nickname" to "备用昵称",
            "random_nick" to "生成随机昵称",
            "username" to "用户名 (身份)",
            "real_name" to "真实姓名",
            "server_password" to "服务器密码",
            "use_sasl" to "使用 SASL 身份验证",
            "sasl_username" to "SASL 用户名",
            "sasl_password" to "SASL 密码",
            "use_bouncer" to "通过 Bouncer 连接",
            "bouncer_network" to "Bouncer 网络/标签",
            "auto_connect" to "启动时自动连接",
            "reconnect_channels" to "自动加入已打开的频道",
            "encoding" to "编码 / 字符集",
            "save_changes" to "保存更改"
        )
    )

    fun getString(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
