package com.personal.ircclient.core.utils

object Localizer {
    private val strings = mapOf(
        "en" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Settings",
            "appearance" to "Appearance",
            "security_privacy" to "Security & Privacy",
            "audio_events" to "Audio & Events",
            "radio" to "Radio",
            "connectivity" to "Connectivity",
            "about" to "About",
            "theme" to "Theme",
            "language" to "Language",
            "identity_color" to "Identity Color",
            "incoming_bubbles" to "Incoming Bubbles",
            "own_bubbles" to "Own Bubbles",
            "high_contrast" to "High Contrast",
            "enable_irc_colors" to "Enable IRC Colors",
            "only_friends_pv" to "Only Friends PV",
            "auto_response" to "Auto-response Message",
            "away_messages" to "Away Messages",
            "default_away" to "Default Away Message",
            "default_back" to "Default Back Message",
            "user_agent" to "UserAgent / RealName",
            "stay_persistent" to "Stay Persistent",
            "search_engine" to "Search Engine URL",
            "use_proxy" to "Use Proxy",
            "save" to "Save",
            "cancel" to "Cancel",
            "join_room" to "Join Room",
            "discover" to "Discover",
            "friends" to "Friends",
            "ignore" to "Ignore",
            "ban" to "Ban",
            "kick" to "Kick",
            "whois" to "Whois",
            "private_chat" to "Private Chat"
        ),
        "es" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Ajustes",
            "appearance" to "Apariencia",
            "security_privacy" to "Seguridad y Privacidad",
            "audio_events" to "Audio y Eventos",
            "radio" to "Radio",
            "connectivity" to "Conectividad",
            "about" to "Acerca de",
            "theme" to "Tema",
            "language" to "Idioma",
            "identity_color" to "Color de Identidad",
            "incoming_bubbles" to "Burbujas Entrantes",
            "own_bubbles" to "Mis Burbujas",
            "high_contrast" to "Alto Contraste",
            "enable_irc_colors" to "Habilitar Colores IRC",
            "only_friends_pv" to "Solo Amigos en PV",
            "auto_response" to "Mensaje de Auto-respuesta",
            "away_messages" to "Mensajes de Ausencia",
            "default_away" to "Mensaje de Ausencia por Defecto",
            "default_back" to "Mensaje de Regreso por Defecto",
            "user_agent" to "UserAgent / Nombre Real",
            "stay_persistent" to "Mantener en Segundo Plano",
            "search_engine" to "URL del Buscador",
            "use_proxy" to "Usar Proxy",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "join_room" to "Entrar en Sala",
            "discover" to "Descubrir",
            "friends" to "Amigos",
            "ignore" to "Ignorar",
            "ban" to "Banear",
            "kick" to "Expulsar",
            "whois" to "Whois",
            "private_chat" to "Chat Privado"
        ),
        "fr" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Paramètres",
            "appearance" to "Apparence",
            "security_privacy" to "Sécurité et Confidentialité",
            "audio_events" to "Audio et Événements",
            "radio" to "Radio",
            "connectivity" to "Connectivité",
            "about" to "À Propos",
            "theme" to "Thème",
            "language" to "Langue",
            "identity_color" to "Couleur d'Identité",
            "incoming_bubbles" to "Bulles Entrantes",
            "own_bubbles" to "Mes Bulles",
            "high_contrast" to "Haut Contraste",
            "enable_irc_colors" to "Activer Couleurs IRC",
            "only_friends_pv" to "Amis Uniquement en PV",
            "auto_response" to "Message d'Auto-réponse",
            "away_messages" to "Messages d'Absence",
            "default_away" to "Message d'Absence par Défaut",
            "default_back" to "Message de Retour par Défaut",
            "user_agent" to "UserAgent / Nom Réel",
            "stay_persistent" to "Rester Persistant",
            "search_engine" to "URL du Moteur de Recherche",
            "use_proxy" to "Utiliser un Proxy",
            "save" to "Enregistrer",
            "cancel" to "Annuler",
            "join_room" to "Rejoindre un Salon",
            "discover" to "Découvrir",
            "friends" to "Amis",
            "ignore" to "Ignorer",
            "ban" to "Bannir",
            "kick" to "Expulser",
            "whois" to "Whois",
            "private_chat" to "Chat Privé"
        ),
        "de" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Einstellungen",
            "appearance" to "Aussehen",
            "security_privacy" to "Sicherheit und Datenschutz",
            "audio_events" to "Audio und Ereignisse",
            "radio" to "Radio",
            "connectivity" to "Konnektivität",
            "about" to "Über",
            "theme" to "Thema",
            "language" to "Sprache",
            "identity_color" to "Identitätsfarbe",
            "incoming_bubbles" to "Eingehende Blasen",
            "own_bubbles" to "Eigene Blasen",
            "high_contrast" to "Hoher Kontrast",
            "enable_irc_colors" to "IRC-Farben Aktivieren",
            "only_friends_pv" to "Nur Freunde im PV",
            "auto_response" to "Auto-Antwort-Nachricht",
            "away_messages" to "Abwesenheitsnachrichten",
            "default_away" to "Standard-Abwesenheitsnachricht",
            "default_back" to "Standard-Rückkehrnachricht",
            "user_agent" to "UserAgent / Realname",
            "stay_persistent" to "Beständig Bleiben",
            "search_engine" to "Suchmaschinen-URL",
            "use_proxy" to "Proxy Verwenden",
            "save" to "Speichern",
            "cancel" to "Abbrechen",
            "join_room" to "Raum Betreten",
            "discover" to "Entdecken",
            "friends" to "Freunde",
            "ignore" to "Ignorieren",
            "ban" to "Bannen",
            "kick" to "Rauswerfen",
            "whois" to "Whois",
            "private_chat" to "Privater Chat"
        ),
        "pt" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Configurações",
            "appearance" to "Aparência",
            "security_privacy" to "Segurança e Privacidade",
            "audio_events" to "Áudio e Eventos",
            "radio" to "Rádio",
            "connectivity" to "Conectividade",
            "about" to "Sobre",
            "theme" to "Tema",
            "language" to "Idioma",
            "identity_color" to "Cor de Identidade",
            "incoming_bubbles" to "Balões de Entrada",
            "own_bubbles" to "Meus Balões",
            "high_contrast" to "Alto Contraste",
            "enable_irc_colors" to "Habilitar Cores IRC",
            "only_friends_pv" to "Apenas Amigos no PV",
            "auto_response" to "Mensagem de Auto-resposta",
            "away_messages" to "Mensagens de Ausência",
            "default_away" to "Mensagem de Ausência Padrão",
            "default_back" to "Mensagem de Retorno Padrão",
            "user_agent" to "UserAgent / Nome Real",
            "stay_persistent" to "Permanecer Persistente",
            "search_engine" to "URL do Buscador",
            "use_proxy" to "Usar Proxy",
            "save" to "Salvar",
            "cancel" to "Cancelar",
            "join_room" to "Entrar na Sala",
            "discover" to "Descobrir",
            "friends" to "Amigos",
            "ignore" to "Ignorar",
            "ban" to "Banir",
            "kick" to "Expulsar",
            "whois" to "Whois",
            "private_chat" to "Chat Privado"
        ),
        "zh" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "设置",
            "appearance" to "外观",
            "security_privacy" to "安全与隐私",
            "audio_events" to "音频与事件",
            "radio" to "电台",
            "connectivity" to "连接性",
            "about" to "关于",
            "theme" to "主题",
            "language" to "语言",
            "identity_color" to "身份颜色",
            "incoming_bubbles" to "接收气泡",
            "own_bubbles" to "自身气泡",
            "high_contrast" to "高对比度",
            "enable_irc_colors" to "启用 IRC 颜色",
            "only_friends_pv" to "仅限好友私聊",
            "auto_response" to "自动回复消息",
            "away_messages" to "离开消息",
            "default_away" to "默认离开消息",
            "default_back" to "默认返回消息",
            "user_agent" to "用户代理 / 真实姓名",
            "stay_persistent" to "保持后台运行",
            "search_engine" to "搜索引擎 URL",
            "use_proxy" to "使用代理",
            "save" to "保存",
            "cancel" to "取消",
            "join_room" to "加入房间",
            "discover" to "发现",
            "friends" to "好友",
            "ignore" to "忽略",
            "ban" to "封禁",
            "kick" to "踢出",
            "whois" to "Whois",
            "private_chat" to "私聊"
        )
    )

    fun getString(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
