package com.personal.ircclient.core.utils

object Localizer {
    private val strings = mapOf(
        "en" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Settings",
            "appearance" to "Appearance",
            "security_privacy" to "Security & Privacy",
            "audio_events" to "Audio & Events",
            "radio" to "Radio",
            "connectivity" to "Connectivity",
            "ascii_phrases" to "ASCII & Phrases",
            "about" to "About",
            "nav_servers" to "Servers",
            "nav_rooms" to "Rooms",
            "nav_privates" to "Privates",
            "nav_settings" to "Settings",
            "theme" to "Theme",
            "language" to "Language",
            "identity_color" to "Identity Color",
            "incoming_bubbles" to "Incoming Bubbles",
            "own_bubbles" to "Own Bubbles",
            "high_contrast" to "High Contrast",
            "enable_irc_colors" to "Enable IRC Colors",
            "only_friends_pv" to "Only Friends PV",
            "auto_response" to "Auto-response Message",
            "link_previews" to "Link Previews",
            "auto_load_images" to "Auto-load Images",
            "away_messages" to "Away Messages",
            "default_away" to "Default Away Message",
            "default_back" to "Default Back Message",
            "user_agent" to "UserAgent / RealName",
            "tts" to "Text-to-Speech",
            "sound_friend" to "Friend Join Sound",
            "sound_pm" to "Private Message Sound",
            "sound_notice" to "Notice Received Sound",
            "sound_mention" to "Mention Sound",
            "events_display" to "Events Display",
            "show_events" to "Show Events in Room",
            "joins" to "Joins",
            "parts" to "Parts",
            "quits" to "Quits",
            "nicks" to "Nick Changes",
            "kicks" to "Kicks",
            "bans" to "Bans",
            "enable_radio" to "Enable Radio Plugin",
            "station" to "Station",
            "stay_persistent" to "Stay Persistent",
            "search_engine" to "Search Engine URL",
            "use_proxy" to "Use Proxy",
            "host" to "Host",
            "port" to "Port",
            "version" to "Version",
            "check_updates" to "Check for Updates",
            "exit_app" to "Exit FenixIRC",
            "no_servers" to "No servers added yet.",
            "no_rooms" to "No active rooms here.",
            "no_privates" to "No private chats yet.",
            "no_ascii" to "No items saved.",
            "join_room" to "Join Room",
            "discover" to "Discover",
            "new_private" to "New Private",
            "friend_list" to "Friend List",
            "search_user" to "Search User",
            "add_new" to "Add New",
            "save" to "Save",
            "cancel" to "Cancel",
            "close" to "Close",
            "whois" to "Whois",
            "private_chat" to "Private Chat",
            "ignore" to "Ignore",
            "delete" to "Delete",
            "edit" to "Edit",
            "connect" to "Connect",
            "disconnect" to "Disconnect",
            "connect_all" to "Connect All",
            "disconnect_all" to "Disconnect All",
            "connect_recents" to "Connect Recents",
            "server_info" to "Server Info",
            "status" to "Status",
            "joined" to "JOINED",
            "banned" to "BANNED",
            "disconnected" to "DISCONNECTED",
            "delete_server" to "Delete Server",
            "delete_server_confirm" to "Are you sure you want to delete this server? History will be lost.",
            "clear_history" to "Clear History",
            "clear_history_confirm" to "Are you sure you want to clear chat history?",
            "loading_image_risk" to "Load Image (Privacy Risk)",
            "youtube_video" to "YouTube Video",
            "social_media_link" to "Social Media Link",
            "modified_by_script" to "Modified by script",
            "typing_message" to "Type a message...",
            "enter_command" to "Enter command...",
            "voice_message" to "Voice Message",
            "voice_message_ext" to "Voice Message (External)",
            "file_message" to "File Sent",
            "attach_file" to "Attach File",
            "uploading" to "Uploading...",
            "self_destruct" to "Self-Destruct Timer",
            "no_limit" to "No Limit",
            "copy_link" to "Copy Link",
            "search" to "Search",
            "music_search" to "Search Music",
            "quick_search" to "Quick Search",
            "kick_user" to "Kick User",
            "ban_user" to "Ban User",
            "op_user" to "Give Op",
            "deop_user" to "Take Op",
            "copy_text" to "Copy Text",
            "copy_nick" to "Copy Nick",
            "notice" to "Notice",
            "user_management" to "User Management",
            "friends" to "Friends",
            "ignored" to "Ignored",
            "silenced" to "Silenced",
            "select_server" to "Select Server",
            "remove" to "Remove",
            "mode" to "Mode",
            "filter_channels" to "Filter Channels",
            "min_users" to "Min Users",
            "apply" to "Apply",
            "users" to "users",
            "no_topic" to "No topic set",
            "add_server" to "Add Server",
            "edit_server" to "Edit Server",
            "connection" to "Connection",
            "identity" to "Identity",
            "advanced_sasl" to "Advanced - SASL",
            "advanced_bouncer" to "Advanced - Bouncer",
            "preferences" to "Preferences",
            "network_name" to "Network Name",
            "server_host" to "Server Host",
            "use_ssl" to "Use SSL/TLS",
            "allow_plain_text" to "Allow Plain Text Connection",
            "nickname" to "Nickname",
            "alt_nickname" to "Alternative Nickname",
            "random_nick" to "Generate Random Nick",
            "username" to "Username",
            "real_name" to "Real Name",
            "server_password" to "Server Password",
            "use_sasl" to "Use SASL Authentication",
            "sasl_username" to "SASL Username",
            "sasl_password" to "SASL Password",
            "use_bouncer" to "Connection through Bouncer",
            "bouncer_network" to "Bouncer Network/Tag",
            "auto_connect" to "Auto-Connect on Start",
            "reconnect_channels" to "Auto-Join Channels",
            "encoding" to "Encoding / Alphabet",
            "save_changes" to "Save Changes",
            "total_users" to "Total users",
            "scripts" to "Scripts",
            "script_name" to "Script Name",
            "trigger_type" to "Trigger Type:",
            "trigger_outgoing" to "Outgoing (Aliases)",
            "trigger_incoming" to "Incoming",
            "script_logic" to "Script Logic",
            "script_support" to "Support: OUT: /alias -> Replacement",
            "no_scripts" to "No scripts created yet.",
            "scripting_engine" to "Scripting Engine",
            "pro_feature_scripts" to "Version Pro feature: Create and edit custom IRC event handlers.",
            "open_script_editor" to "Open Script Editor",
            "secure_requested" to "Secure chat requested",
            "accept_generate_key" to "Accept & Generate Key",
            "waiting_secure_accept" to "Waiting for user to accept secure chat...",
            "add_station" to "Add Station",
            "station_url" to "Station URL",
            "custom_stations" to "Custom Stations",
            "help_tutorials" to "Help & Tutorials",
            "open_manual" to "View User Manual",
            "online_tutorials" to "Online Tutorials",
            "support_web" to "Visit Support Website",
            "check_version" to "Check for Updates",
            "already_latest" to "You are using the latest version.",
            "new_version_available" to "A new version is available!",
            "resource_usage_warning" to "Resource Consumption Warning",
            "resource_usage_desc" to "The following options may increase battery and data consumption: Auto-loading images, background connection (Stay Persistent), and frequent PING intervals. Use them wisely on limited networks.",
            "high_resource" to "High Usage",
            "made_with_gemini" to "Made with Gemini AI",
            "scripts" to "Scripts",
            "script_name" to "Script Name",
            "trigger_type" to "Trigger Type:",
            "trigger_outgoing" to "Outgoing (Aliases)",
            "trigger_incoming" to "Incoming",
            "script_logic" to "Script Logic",
            "script_support" to "Support: OUT: /alias -> Replacement",
            "no_scripts" to "No scripts created yet.",
            "scripting_engine" to "Scripting Engine",
            "pro_feature_scripts" to "Version Pro feature: Create and edit custom IRC event handlers.",
            "open_script_editor" to "Open Script Editor",
            "privacy_policy_title" to "Privacy & Security Commitment",
            "privacy_policy_desc" to "FenixIRC is a non-profit project. We do NOT collect, store, or traffic your data. All your communications and credentials remain on your device or are sent directly to the IRC servers you choose. Our only interest is the work itself and giving back to the computer community what we have received from it. Warning: IRC is an open protocol; use the 'Secure Chat' (Pro) feature for end-to-end encryption in private messages.",
            "privacy_policy_short" to "No data collection. No tracking. Pure Open Source philosophy."
        ),
        "es" to mapOf(
            "app_name" to "FenixIRC",
            "settings" to "Ajustes",
            "appearance" to "Apariencia",
            "security_privacy" to "Seguridad y Privacidad",
            "audio_events" to "Audio y Eventos",
            "radio" to "Radio",
            "connectivity" to "Conectividad",
            "ascii_phrases" to "ASCII y Frases",
            "help_tutorials" to "Ayuda y Tutoriales",
            "open_manual" to "Ver Manual de Usuario",
            "online_tutorials" to "Tutoriales Online",
            "support_web" to "Visitar Web de Soporte",
            "check_version" to "Buscar Actualizaciones",
            "already_latest" to "Ya tienes la última versión.",
            "new_version_available" to "¡Hay una nueva versión disponible!",
            "resource_usage_warning" to "Aviso de Consumo de Recursos",
            "resource_usage_desc" to "Las siguientes opciones pueden aumentar el consumo de batería y datos: Auto-carga de imágenes, mantener conexión en segundo plano (Stay Persistent) e intervalos de PING frecuentes. Úsalas con moderación en redes limitadas.",
            "high_resource" to "Alto Consumo",
            "made_with_gemini" to "Hecho con Gemini AI",
            "scripts" to "Scripts",
            "script_name" to "Nombre del Script",
            "trigger_type" to "Tipo de Disparador:",
            "trigger_outgoing" to "Saliente (Aliases)",
            "trigger_incoming" to "Entrante",
            "script_logic" to "Lógica del Script",
            "script_support" to "Soporta: OUT: /alias -> Reemplazo",
            "no_scripts" to "No hay scripts creados.",
            "scripting_engine" to "Motor de Scripts",
            "pro_feature_scripts" to "Función Pro: Crea y edita manejadores de eventos IRC.",
            "open_script_editor" to "Abrir Editor de Scripts",
            "about" to "Acerca de",
            "nav_servers" to "Servidores",
            "nav_rooms" to "Salas",
            "nav_privates" to "Privados",
            "nav_settings" to "Ajustes",
            "theme" to "Tema",
            "language" to "Idioma",
            "identity_color" to "Color de Identidad",
            "incoming_bubbles" to "Burbujas Entrantes",
            "own_bubbles" to "Mis Burbujas",
            "high_contrast" to "Alto Contraste",
            "enable_irc_colors" to "Habilitar Colores IRC",
            "only_friends_pv" to "Solo Amigos en PV",
            "auto_response" to "Mensaje de Auto-respuesta",
            "link_previews" to "Previsualizar Enlaces",
            "auto_load_images" to "Auto-cargar Imágenes",
            "away_messages" to "Mensajes de Ausencia",
            "default_away" to "Mensaje de Ausencia por Defecto",
            "default_back" to "Mensaje de Regreso por Defecto",
            "user_agent" to "UserAgent / Nombre Real",
            "tts" to "Texto a Voz",
            "sound_friend" to "Sonido Entrada Amigo",
            "sound_pm" to "Sonido Mensaje Privado",
            "sound_notice" to "Sonido de Aviso",
            "sound_mention" to "Sonido de Mención",
            "events_display" to "Visualización de Eventos",
            "show_events" to "Mostrar Eventos en Sala",
            "joins" to "Entradas",
            "parts" to "Salidas",
            "quits" to "Desconexiones",
            "nicks" to "Cambios de Nick",
            "kicks" to "Expulsiones",
            "bans" to "Baneos",
            "enable_radio" to "Habilitar Plugin de Radio",
            "station" to "Estación",
            "stay_persistent" to "Mantener Conexión",
            "search_engine" to "URL del Buscador",
            "use_proxy" to "Usar Proxy",
            "host" to "Host",
            "port" to "Puerto",
            "version" to "Versión",
            "check_updates" to "Buscar Actualizaciones",
            "exit_app" to "Salir de FenixIRC",
            "no_servers" to "No hay servidores añadidos.",
            "no_rooms" to "No hay salas activas.",
            "no_privates" to "No hay chats privados.",
            "no_ascii" to "No hay elementos guardados.",
            "join_room" to "Entrar en Sala",
            "discover" to "Descubrir",
            "new_private" to "Nuevo Privado",
            "friend_list" to "Lista de Amigos",
            "search_user" to "Buscar Usuario",
            "add_new" to "Añadir Nuevo",
            "save" to "Guardar",
            "cancel" to "Cancelar",
            "close" to "Cerrar",
            "whois" to "Whois",
            "private_chat" to "Chat Privado",
            "ignore" to "Ignorar",
            "delete" to "Eliminar",
            "edit" to "Editar",
            "connect" to "Conectar",
            "disconnect" to "Desconectar",
            "connect_all" to "Conectar Todo",
            "disconnect_all" to "Desconectar Todo",
            "connect_recents" to "Conectar Recientes",
            "server_info" to "Info del Servidor",
            "status" to "Estado",
            "joined" to "CONECTADO",
            "banned" to "BANEADO",
            "disconnected" to "DESCONECTADO",
            "delete_server" to "Eliminar Servidor",
            "delete_server_confirm" to "¿Estás seguro de eliminar este servidor? El historial se perderá.",
            "clear_history" to "Borrar Historial",
            "clear_history_confirm" to "¿Estás seguro de borrar el historial de chat?",
            "loading_image_risk" to "Cargar Imagen (Riesgo de Privacidad)",
            "youtube_video" to "Vídeo de YouTube",
            "social_media_link" to "Enlace de Redes Sociales",
            "modified_by_script" to "Modificado por script",
            "typing_message" to "Escribe un mensaje...",
            "enter_command" to "Escribe un comando...",
            "voice_message" to "Mensaje de voz",
            "voice_message_ext" to "Mensaje de voz (Externo)",
            "file_message" to "Archivo Enviado",
            "attach_file" to "Adjuntar Archivo",
            "uploading" to "Subiendo...",
            "self_destruct" to "Temporizador de auto-destrucción",
            "no_limit" to "Sin Límite",
            "copy_link" to "Copiar Enlace",
            "search" to "Buscar",
            "music_search" to "Buscar Música",
            "quick_search" to "Búsqueda Rápida",
            "kick_user" to "Expulsar Usuario",
            "ban_user" to "Banear Usuario",
            "op_user" to "Dar Op",
            "deop_user" to "Quitar Op",
            "copy_text" to "Copiar Texto",
            "copy_nick" to "Copiar Nick",
            "notice" to "Aviso",
            "user_management" to "Gestión de Usuarios",
            "friends" to "Amigos",
            "ignored" to "Ignorados",
            "silenced" to "Silenciados",
            "select_server" to "Seleccionar Servidor",
            "remove" to "Eliminar",
            "mode" to "Modo",
            "filter_channels" to "Filtrar Canales",
            "min_users" to "Mínimo de Usuarios",
            "apply" to "Aplicar",
            "users" to "usuarios",
            "no_topic" to "Sin tema definido",
            "add_server" to "Añadir Servidor",
            "edit_server" to "Editar Servidor",
            "connection" to "Conexión",
            "identity" to "Identidad",
            "advanced_sasl" to "Avanzado - SASL",
            "advanced_bouncer" to "Avanzado - Bouncer",
            "preferences" to "Preferencias",
            "network_name" to "Nombre de Red",
            "server_host" to "Host del Servidor",
            "use_ssl" to "Usar SSL/TLS",
            "allow_plain_text" to "Permitir Conexión en Texto Plano",
            "nickname" to "Nickname",
            "alt_nickname" to "Nickname Alternativo",
            "random_nick" to "Generar Nick Aleatorio",
            "username" to "Usuario (Identidad)",
            "real_name" to "Nombre Real",
            "server_password" to "Contraseña de Servidor",
            "use_sasl" to "Usar Autenticación SASL",
            "sasl_username" to "Usuario SASL",
            "sasl_password" to "Contraseña SASL",
            "use_bouncer" to "Conexión vía Bouncer",
            "bouncer_network" to "Red/Tag de Bouncer",
            "auto_connect" to "Auto-Conectar al Inicio",
            "reconnect_channels" to "Reconectar Canales Abiertos",
            "encoding" to "Codificación / Alfabeto",
            "save_changes" to "Guardar Cambios",
            "total_users" to "Usuarios totales",
            "scripts" to "Scripts",
            "script_name" to "Nombre del Script",
            "trigger_type" to "Tipo de Disparador:",
            "trigger_outgoing" to "Saliente (Aliases)",
            "trigger_incoming" to "Entrante",
            "script_logic" to "Lógica del Script",
            "script_support" to "Soporta: OUT: /alias -> Reemplazo",
            "no_scripts" to "No hay scripts creados.",
            "scripting_engine" to "Motor de Scripts",
            "pro_feature_scripts" to "Función Pro: Crea y edita manejadores de eventos IRC.",
            "open_script_editor" to "Abrir Editor de Scripts",
            "secure_requested" to "Chat seguro solicitado",
            "accept_generate_key" to "Aceptar y Generar Llave",
            "waiting_secure_accept" to "Esperando que el usuario acepte el chat seguro...",
            "add_station" to "Añadir Estación",
            "station_url" to "URL de la Estación",
            "custom_stations" to "Estaciones Personalizadas",
            "privacy_policy_title" to "Compromiso de Privacidad y Seguridad",
            "privacy_policy_desc" to "FenixIRC es un proyecto sin fines de lucro. NO recolectamos, almacenamos ni traficamos con tus datos. Todas tus comunicaciones y credenciales permanecen en tu dispositivo o se envían directamente a los servidores IRC que elijas. Nuestro único interés es el trabajo en sí mismo y aportar a la comunidad informática algo de lo que hemos recibido de ella. Advertencia: IRC es un protocolo abierto; utiliza la función 'Chat Seguro' (Pro) para cifrado de extremo a extremo en mensajes privados.",
            "privacy_policy_short" to "Sin recolección de datos. Sin rastreo. Filosofía Open Source pura."
        )
    )

    fun getString(key: String, lang: String): String {
        return strings[lang]?.get(key) ?: strings["en"]?.get(key) ?: key
    }
}
